# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
# NeoForge
neo_version=26.1.2.97
# houblonneux
mod_id=houblonneux
mod_name=Houblonneux
mod_license=MIT
mod_version=26.1.2-0.0.7
mod_group_id=com.unpainperdu.houblonneux
# other mod
#only for test mod version
jei_version=29.29.0.77